#!/bin/sh

# requires node and npm installed

mkdir -p tools
cp ../build/out/node/opac.node.js tools
cp coverage.js tools
cp UTF-8-test.txt tools
cd tools || exit 1
if [ ! -d "node_modules" ]; then
	npm install --save-dev c8 jsbn big.js
fi
# coverage report will be in "coverage" directory
npx c8 -r html node coverage.js
cd - > /dev/null
