#!/bin/sh

# requires node and npm installed

cd ../build || exit 1
CCJAR="0" ./build
cd - > /dev/null

mkdir -p tools
cp ../build/out/node/opac.node.js tools
cp coverage.js tools
cp UTF-8-test.txt tools
cd tools || exit 1
if [ ! -d "node_modules" ]; then
	npm install --save-dev c8 jsbn big.js
fi
echo "running coverage tests..."
# coverage report will be in "coverage" directory
node node_modules/c8/bin/c8.js -r html node coverage.js
cd - > /dev/null
